[[ParU]]
arch = "aarch64"
git-tree-sha1 = "b616f0043c4ae1fb95e33b0485e1bbc31ee5dfd8"
os = "macos"

    [[ParU.download]]
    sha256 = "db483fe16507320d165017a0dc494d84104f219d842a8fa76e318304c98e1f54"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.aarch64-apple-darwin.tar.gz"
[[ParU]]
arch = "aarch64"
git-tree-sha1 = "807444f2bbd56d31f777a716eabe17cc9eecd32a"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "7958410fff8b7b7b968ada909d23231ac588c41239724731eb1374833cc610a1"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.aarch64-linux-gnu.tar.gz"
[[ParU]]
arch = "aarch64"
git-tree-sha1 = "bcd1e55a533b1f7cffd4ec3b0a9afe239a6662a3"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "1df62c435c83eed268d6f19e10a18b57e350005a139efacd8d626ad38edcde9a"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.aarch64-linux-musl.tar.gz"
[[ParU]]
arch = "aarch64"
git-tree-sha1 = "1735b081c1bfeadec645141b3e0e149888230aa2"
os = "freebsd"

    [[ParU.download]]
    sha256 = "3c695c5f03918a9744c6ca15fc6ded3d79e184945960bb005524ae44c21fc806"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.aarch64-unknown-freebsd.tar.gz"
[[ParU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c69a1a862de2c0ae4efbba44a916c935d41f27f5"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "59e056ce4776e0f4b973939f97bbf3a15cf4afdcf5e7e5387cea4971f9dcfdae"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[ParU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d4490f74c75e1726dd77570801bc742cb3c921d9"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "55ade3c9203e8a562098e86d5e4c8d8f6763acce141b78bd1bbff3cc3c059c30"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.armv6l-linux-musleabihf.tar.gz"
[[ParU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "489b431b0536fd5ec88726d6bb9c9968bb7f02ea"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "cd9ce683c1d66766a6f59a534e096c2cec8ad5af6128a58067fd187a1294fdeb"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[ParU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ee780c92adbc7bc0f614a1c59b8b8e964f04db92"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "aace4a6c6172cf6b1937bb2bdbea6b2ff2a6b906abc82c7f9dfbaf4924e9f57e"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[ParU]]
arch = "i686"
git-tree-sha1 = "29b141e7931508ef3725a684a1bf4733f0b58584"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "aba1a38ff51cbcb92464cd125ff80d20d8cf18f06cc5b946a9c039c95683ce49"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.i686-linux-gnu.tar.gz"
[[ParU]]
arch = "i686"
git-tree-sha1 = "412a656ec8eb82b8cddf20340eabbb34be7772a0"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "ce638244575a0e7cf35997254490c0a759e170c7025d2f4d437d5c200285064c"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.i686-linux-musl.tar.gz"
[[ParU]]
arch = "i686"
git-tree-sha1 = "752c7cd45be7c29e02865683ac4a971a29a042a0"
os = "windows"

    [[ParU.download]]
    sha256 = "16a74fab5dbaa4087454176e0ddd2e9541788b9d986c0236a4f8e5dfa65eefda"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.i686-w64-mingw32.tar.gz"
[[ParU]]
arch = "powerpc64le"
git-tree-sha1 = "81a54911f692941357a11a7c44bda88d4cf63ef5"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "22e951ca84b582b150fe248108519bf1ffe39d6e5a0c7c24b3ee0272dc777fa2"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "9d9f3aeae05b9389db10aa1a30a71f31d84bdbfb"
os = "macos"

    [[ParU.download]]
    sha256 = "608cafe4fbdb3aa14eede9bad381dccd63eab46c19e1f14bbe60fdee7ed07299"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.x86_64-apple-darwin.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "23f9154338d90ddaf6022a25a137bddc55e09f08"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "5a87f7431337ce737eab36d049dee84f1bc02e927e81db26f21eda972900a7f4"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.x86_64-linux-gnu.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "b77ea60675c81dc9439e8f9ea27e7e0d4d9060e1"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "ed0d64d17186a137cf4dd5403380ea995c605fd5f819d778de0de7b9b02930a9"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.x86_64-linux-musl.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "66c68bf89fd862b84a924927b526b613873b079b"
os = "freebsd"

    [[ParU.download]]
    sha256 = "440b40caec77c05937dc69fbc933263d509bb217c34b5e29c1945cf7e9d20cd1"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "1d7fcae6ea45242b91748565275d2035e0caca93"
os = "windows"

    [[ParU.download]]
    sha256 = "52abe4687ae7b7108af83035bdc9dfcf9053a0f6234cb20c70b0d8933b199fd9"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.x86_64-w64-mingw32.tar.gz"
