[[ParU]]
arch = "aarch64"
git-tree-sha1 = "2d3d42923883a3107dbdac30ba97481eac4e901e"
os = "macos"

    [[ParU.download]]
    sha256 = "8555b2bd9a4472244cec59466a14183264e1052be78988e30598318755a145c9"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.aarch64-apple-darwin.tar.gz"
[[ParU]]
arch = "aarch64"
git-tree-sha1 = "887a68a65726976b8cdad2059b7bc5eeb4accf1c"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "07ebe1ea47801e6658fefa53cf1359340f23f6e926823d47be84e27fb7be84b3"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.aarch64-linux-gnu.tar.gz"
[[ParU]]
arch = "aarch64"
git-tree-sha1 = "1def76c22eacb93299be290ae3811992d89aac39"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "40b3c33550ba4c64b8eb3c23a4f23721d2908f1e8a7bf8c2894e29c2334d2766"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.aarch64-linux-musl.tar.gz"
[[ParU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "230acfb13835d21437a2a08d586165ce275421ef"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "dd41b4eed44ced02e1471215dbac9129dbc5548bc43524a4508d673d9c4cf1e6"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.armv6l-linux-gnueabihf.tar.gz"
[[ParU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0899ac7fc73085d6ad88ff07b502e8314014e951"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "be9620e782386e6dfb237ca0ff1f1dffefadbb1e508a24d09c6819f718205346"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.armv6l-linux-musleabihf.tar.gz"
[[ParU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cbabe4be7b66404d3878424f68d963ce8134597a"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "fd38ed32dfd16258e85a096ac725e126f8a089a20f6579e18ec19e7f47d9e670"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.armv7l-linux-gnueabihf.tar.gz"
[[ParU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b57cfe391526bd7e54a3bd634fa37307635ae76c"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "43fdda1b2d7ccef5c86d739964cb23ad4960e31bc539f53085e9181d07c5bd59"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.armv7l-linux-musleabihf.tar.gz"
[[ParU]]
arch = "i686"
git-tree-sha1 = "3585a5e2ddd43d3371d93a866ebdf2dbad967d78"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "4fbce3367e9e53ce954eff70f247b6e3a0cb26d6f7521f7599de7f0750f7bbbe"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.i686-linux-gnu.tar.gz"
[[ParU]]
arch = "i686"
git-tree-sha1 = "01d87de8b78b54a37ffdbe0429bc56f8908043b1"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "31182758f37912316559ffc416059a47cc0f2080cfdeb2a74a7833a568427dc5"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.i686-linux-musl.tar.gz"
[[ParU]]
arch = "i686"
git-tree-sha1 = "7026a518f4738ab6615d4a315fba78cec3cb90ce"
os = "windows"

    [[ParU.download]]
    sha256 = "6a032caba94f1b76bcd93d79dd53992224ffa87176f4a6348afc11fe2acfc1c0"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.i686-w64-mingw32.tar.gz"
[[ParU]]
arch = "powerpc64le"
git-tree-sha1 = "2b75f78131ac863e8d0ef027de57f9f4dc3040b8"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "eb32e093286cf81737987ae4c6d172965c25e3ef906385871ec670ec43e0815f"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.powerpc64le-linux-gnu.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "9698d8438131a68c815eb22171cd0127e215f75a"
os = "macos"

    [[ParU.download]]
    sha256 = "c4de067d85324d889b710c1ca74fde617a2910d560288634de0b249f839c6da0"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.x86_64-apple-darwin.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "e81b9a555dd2a5095b19b569df6aea2efb84bd42"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "bda5f5a4b926f121ee62f84762c36e64cd37c50deebbe820e9b14d8d7af645df"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.x86_64-linux-gnu.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "acfad34c631eaafa36d6d7838d7a2a4f38f0c66e"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "985c97bba0aa4c4c12a1d1987260ba50bca1634e17d0c6d0a1f91db436a591bc"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.x86_64-linux-musl.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "655c53c93a0621d531914ea8e0c9f8622ec4982f"
os = "freebsd"

    [[ParU.download]]
    sha256 = "68fbe6f73736be59dd8fdabdda8616af13db7aed606deaeb6eed8cfc777d068e"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.x86_64-unknown-freebsd.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "a8cb67e3d5233280b05adcb87e458d00a2b2ef37"
os = "windows"

    [[ParU.download]]
    sha256 = "d9dea598ed3c19b19474cb8afad56e7cadff5d8a2a1ff5668bab1a3cac272d26"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v0.1.3+0/ParU.v0.1.3.x86_64-w64-mingw32.tar.gz"
