[[ParU]]
arch = "aarch64"
git-tree-sha1 = "8f54174f8e63ccef5c22284ca9fcd3763d065e20"
os = "macos"

    [[ParU.download]]
    sha256 = "e748d92cda92f3eed37d7a858635215065247b9d940f4a147b1ef05781850232"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.aarch64-apple-darwin.tar.gz"
[[ParU]]
arch = "aarch64"
git-tree-sha1 = "5dadb426039eef30f52e614f4341a9045be39340"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "2a868da477feaeb60f45b36186372711d6135b35bceea109b8c280908e6cae8b"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.aarch64-linux-gnu.tar.gz"
[[ParU]]
arch = "aarch64"
git-tree-sha1 = "6b7243b8af4fb454fc69ac97901f4b8614284f56"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "7f86e40fc882aac443f88c8bde592d4a49533484661ce19a7c83a318257f46de"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.aarch64-linux-musl.tar.gz"
[[ParU]]
arch = "aarch64"
git-tree-sha1 = "32616a06ac1d691f86b01993ac69da3fb14abdae"
os = "freebsd"

    [[ParU.download]]
    sha256 = "878fcd39ec866b5d5d7eb767390875a08f2dd5a860cbab84a18780831c5c304d"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.aarch64-unknown-freebsd.tar.gz"
[[ParU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "25f704516ed450b23de313fe1d37b69d93a15883"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "260077790fec0d1f9cf05b40494aacf2ba4d466c436666d141d06acfc78f6f44"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[ParU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f0ca45afdd52579e18fc3f97e35e919bd25a5d68"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "f1947ae6181b54b3f14cf033e718b5c359e249721c2b4c001040d18a8a430e5e"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.armv6l-linux-musleabihf.tar.gz"
[[ParU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "88edb4405dec9553f47a20247cee69a1b8c471d4"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "774816fb0162355ec6ab790ddf09c1897e4ef9c35ca59ac021855094d1665867"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[ParU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a2ac58f96b04b434d73a744204b112deeafcc8f5"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "4a4a7ff30bc09dcad7bf82a86f4e286a14b64eb5bf5a1bafd624c8c08e0a9fcc"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[ParU]]
arch = "i686"
git-tree-sha1 = "8b5646e4b4ff736377b6d0e7808933ad91b17cdb"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "05d3e802449ac8541ad0cbee153e253317c9ea5d3e4819ea2a5c5f582cee69a8"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.i686-linux-gnu.tar.gz"
[[ParU]]
arch = "i686"
git-tree-sha1 = "81986fb7d8889ea25257b98db382e791737c1c51"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "cbaff242d43bf01e2d3bedc226112a2151926633736535c2aa52c356360788fc"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.i686-linux-musl.tar.gz"
[[ParU]]
arch = "i686"
git-tree-sha1 = "fdf3b792da548ce2134df5edf4beb4bad1b5c72f"
os = "windows"

    [[ParU.download]]
    sha256 = "e0d9d195205011274414a17a441fc8fc05407f96c30de497a886194a9302dfed"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.i686-w64-mingw32.tar.gz"
[[ParU]]
arch = "powerpc64le"
git-tree-sha1 = "f4b9d88db5c18f373a63bd818cab84d8ab459726"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "383a66bf04415fc7ba6c7a667981db99abe329fb5a5f0cf7b48d0cebdbd9a276"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[ParU]]
arch = "riscv64"
git-tree-sha1 = "f9572ed2a7e3aae25c642753cb74a9fb03a8b314"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "e73ded2993cefd38f92d3663bd75051040f0338bc0f5a3cbac55aa13d1469fca"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.riscv64-linux-gnu.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "01b3fd0c2402cb70fcaf1e9b475fdb6260562bb3"
os = "macos"

    [[ParU.download]]
    sha256 = "9b6f21690a0b15548c9dc996bca9020359e22162ecffde6f0ea85fe70144a874"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.x86_64-apple-darwin.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "5d7579982a8c9a7aaf03f4b395c3830650a8dc30"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "ee7d810bc98e6ceed9c67d96658aa5283420dedc3c620497d78c71dd4079ee50"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.x86_64-linux-gnu.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "f7ed5f5ba9aceb3ab4551c88cbe0fe160d69b4e1"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "899e98a3f46e58a78fc7c6d727975dcbbdbe21899ce3a362f0635689e37966ca"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.x86_64-linux-musl.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "e2542897da39cdfff0bb460497fd2e5954824404"
os = "freebsd"

    [[ParU.download]]
    sha256 = "04da56377c158d63f8580d69d525c90901e1d2547ef4a3d541aa7c357269bb91"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "493844b7e655afc3def4689b887a2962faa69468"
os = "windows"

    [[ParU.download]]
    sha256 = "732ac4aff7cc2ddc528b401a4a2a407d0a192f2506f2bb31c1bfa965b76e06a1"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+0/ParU.v1.0.0.x86_64-w64-mingw32.tar.gz"
