[[ParU]]
arch = "aarch64"
git-tree-sha1 = "8dd9862f492add16b0eccdbf021cf157e567519e"
os = "macos"

    [[ParU.download]]
    sha256 = "66e78185d938bc6bd5c01d44286e2c06d48a38da5ee7d4fc16703ceebb839f98"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.aarch64-apple-darwin.tar.gz"
[[ParU]]
arch = "aarch64"
git-tree-sha1 = "0d31da089a366c347fce3943a0a345bfb2c609b1"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "6a412ec5dbb8e46633fc0740769f71795a324e07974becea0678950b66950e79"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.aarch64-linux-gnu.tar.gz"
[[ParU]]
arch = "aarch64"
git-tree-sha1 = "674063e2140cdb65f25d63459bbf549d76ad0a9a"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "66a3bfa058004e529027f1a76b4aeb78fc26eae197d2654f64225cdb1cb211bb"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.aarch64-linux-musl.tar.gz"
[[ParU]]
arch = "aarch64"
git-tree-sha1 = "67ea949fc26fe13ddc77c2758dedba1543d7be4d"
os = "freebsd"

    [[ParU.download]]
    sha256 = "c5ec5ebcc72b1290464191cf58a6cc89dd1a240ff19b52912ee7fc458989399c"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.aarch64-unknown-freebsd.tar.gz"
[[ParU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1e43210e191e4209795e1e5bc5e165b630b679e3"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "badf6a665657c5636785336e4f0be7b353b73f373f43700a84eb6836d96511ea"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[ParU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1f9d454acfa6b8caaffafa2d73ed3f4183ac0067"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "4bf9ed380e6b1c0abcd4ed42a356c5f4bb5c2eea40f7a6467f233cb799c79a51"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.armv6l-linux-musleabihf.tar.gz"
[[ParU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c270aabdfa09f1badb3ae54080ccd9f825ff0f36"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "7125ea8114d71938465072548f9215fc9791dd97ffb58334f14a00cc2747e5f5"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[ParU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "39e43e939c7c8f7d366a03739f4a7a916a62dd44"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "8ac9ed876b6b0edbcb17e4f62fb658f7684d2ad22b29b4e0c3deae10b118162b"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[ParU]]
arch = "i686"
git-tree-sha1 = "cf706abe2cecaac551da740298dfeb944e58c6df"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "a498b58c56d30fe6cfd95d84d46d2123b3cc23b1bb4b0c27d9d1a1b4b737a473"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.i686-linux-gnu.tar.gz"
[[ParU]]
arch = "i686"
git-tree-sha1 = "b6b3679b8d7f8b6496ad941cbf677016a98e5137"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "c4e94b92d87823f0feb5f1a9d4a9fe3af87730291979d95890d1238cc82e1af0"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.i686-linux-musl.tar.gz"
[[ParU]]
arch = "i686"
git-tree-sha1 = "22733c68c6109d3b6e86960fdc00a3d7eb46a4a7"
os = "windows"

    [[ParU.download]]
    sha256 = "313859fea72af3f86b04078ec88469874317233eaf8061b5b846a8e3fae04f78"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.i686-w64-mingw32.tar.gz"
[[ParU]]
arch = "powerpc64le"
git-tree-sha1 = "3052cc8747388883bae558233ebb02c4c311e337"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "531e8f7e9fa60d1c009f2d6c2325683370814bd1f599f42841f4d65277f433b8"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[ParU]]
arch = "riscv64"
git-tree-sha1 = "f51b9cf5e0d96f33a6ffbd5130af8900a53ca6b4"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "840be5064d0ca0a27b5af3ea2b895817583d43e25e8d928e0c64ce183ea3c6f6"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.riscv64-linux-gnu.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "a1ebddbcef34376077084369ee4b854e7b69072b"
os = "macos"

    [[ParU.download]]
    sha256 = "885b057469065ad3af97f5234f294a753616d6b016cb819214951ea2abe25d09"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.x86_64-apple-darwin.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "d218a04a31f0901144e625f450fea7e1aa9321b9"
libc = "glibc"
os = "linux"

    [[ParU.download]]
    sha256 = "2b4225b3dc9184039ddbc80ec78675650f520cc3f86d40eed14566fea9a487fc"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.x86_64-linux-gnu.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "78da1230512bea545d31d678315d9f5c2746aeed"
libc = "musl"
os = "linux"

    [[ParU.download]]
    sha256 = "2e94163936de68b52266aff23890c534fbf9b9ea25015e96b9df8f716c1795d2"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.x86_64-linux-musl.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "b5a8b9d7df82a567967114f18edc935f81008247"
os = "freebsd"

    [[ParU.download]]
    sha256 = "f007abe12e605654b19cb6c32b8e615f82a2d91597c547acaa1d93f3c8878c57"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[ParU]]
arch = "x86_64"
git-tree-sha1 = "c59e4f90a26e546e9742afb525e799cfcafafec3"
os = "windows"

    [[ParU.download]]
    sha256 = "7ef435ae8555696461832632e159679d7486ff3434b079288bff1d3ec284b27c"
    url = "https://github.com/JuliaBinaryWrappers/ParU_jll.jl/releases/download/ParU-v1.0.0+1/ParU.v1.0.0.x86_64-w64-mingw32.tar.gz"
