# Autogenerated wrapper script for ParU_jll for armv7l-linux-gnueabihf
export libparu

using libblastrampoline_jll
using CompilerSupportLibraries_jll
using SuiteSparse_jll
JLLWrappers.@generate_wrapper_header("ParU")
JLLWrappers.@declare_library_product(libparu, "libparu.so.0")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, CompilerSupportLibraries_jll, SuiteSparse_jll)
    JLLWrappers.@init_library_product(
        libparu,
        "lib/libparu.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
